### ISSUE TITLE
Not an issue: How to make it work with Windows

### ISSUE THREAD

**Issue by foreachthing** [icarecti/chatgpt_macro_for_texstudio#1]
Just follow these instructions: https://github.com/icarecti/chatgpt_macro_for_texstudio

But then change the imported ChatGPT macro, by replacing line 31 with this line (TeXstudio: Macros -> Edit)
`cmd = system(command + "' > /dev/null");`
This line was `cmd = system("bash -c 'exec " + command + "' > /dev/null");` and there's no bash on my Windows machine.

Note: all paths to python and the script have forward slashes like so:
```
// #########################################################################
// Set the path to Python3 and the Python script
var python_path = "C:/Users/User/AppData/Local/Programs/Python/Python311/python.exe"; // *** edit this line **
var script_path = "h:/dev/openAI/openai_python_script.py"; // *** edit this line **
// #########################################################################
```

**Comment by icarecti** [comment]
Thank you for your input. Will update the readme regarding the path in Windows. 

Regarding the bash. You are right. It is not required. In one macro i removed it. Forgot it in the second on.

**Comment by foreachthing** [comment]
Thanks for your script!
This is really fun to play around with. I yet have to find practical use ;-)

**Comment by icarecti** [comment]
You are welcome. 
I changed the readme and removed the bash from the macro.

Same here. It really is fun seeing the text appearing in front of you.
