### ISSUE TITLE
sys.argv[1] gets split into single words

### ISSUE THREAD

**Issue by Niklas123Niklas** [icarecti/chatgpt_macro_for_texstudio#3]
Hi there,

thanks for the nice interface to chatGPT in TeXStudio. I had the problem that the message got split up into multiple sys.argv elements with one word each. I think, it occured if I was using dots or questionmarks in the message. This resulted in a wrong promt, as only the first element/first word was used. 

I am not very experienced in python, but with `promt = " ".join(sys.argv[1:])` in `openai_python_script.py`, the problem was solved. I don´t know, if this may create other issues, but so far there were none.

Cheers
Niklas

**Comment by icarecti** [comment]
Thank you for your feedback. I changed the script. While I was at it I also updated the script to use the latest syntax of the openAI library.

Greetings!
